# Generated by Django 2.0 on 2019-03-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='rate',
            name='tenant_id',
            field=models.ManyToManyField(to='api.Tenant'),
        ),
    ]
