# Generated by Django 2.0 on 2019-03-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190330_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='user_id',
            field=models.ManyToManyField(to='api.User'),
        ),
    ]
